name: PR Labeler

on:
  workflow_dispatch:
    inputs:
      PR:
        description: PR Number
        required: true
  pull_request_target:
    branch: Development

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"