name: Build Release

on:
  release:
    types:
      - published
    branches:
      - master
  workflow_dispatch:
    
jobs:
  build:
    name: Build & Package Mod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x    
        
      - name: Build Artifact
        run: |
          dotnet build Source -c Release

      - name: Package Mod
        run: |
          mkdir CombatOverhaul
          cp -r Assemblies/ About/ Defs/ Languages/ Patches/ Royalty/ Ideology/ Sounds/ Textures/ LoadFolders.xml README.md SupportedThirdPartyMods.md CombatOverhaul
          zip -9 -r CombatOverhaul.zip CombatOverhaul
          
      - name: Upload Package
        id: upload-package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: CombatOverhaul.zip
          asset_name: CombatOverhaul-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/octet-stream
  
  message:
    name: "Discord Message"
    runs-on: "ubuntu-latest"
    needs: package
    steps:
      - uses: "hugoalh/send-discord-webhook-ghaction@v4.0.0"
        with:
          key: "${{ secrets.DISCORD_URL }}"
          payload: |
            {
              "content": "<@133602605220888576>",
              "embeds": [
                {
                  "title": "[Release] Combat Overhaul ${{ github.event.release.name }}",
                  "url": "${{ github.event.release.html_url }}",
                  "description": "If you want to read the full changelog please click on the title of this message or if you want to directly download the mod / subscribe to steam pelase use the links provided below.",
                  "fields": [
                    {
                      "name": "Downloads",
                      "value": "[GitHub](${{ env.GH_DL }}) - [Steam](${{ env.SM_DL }})"
                    }
                  ],
                  "thumbnail": {
                    "url": "https://cdn.discordapp.com/attachments/584381284114104352/924355531810951188/Dross2.png"
                  }
                }
              ]
            }